name: Release Training SDK

on:
  push:
    branches:
      - "v*-branch"
  workflow_dispatch:

jobs:
  release-sdk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          pip install PyGithub==1.55 twine==3.4.1
      
      - name: Update version in SDK files
        run: |
          VERSION="${{ github.ref_name }}"
          # Remove 'v' prefix and '-branch' suffix
          VERSION=${VERSION#v}
          VERSION=${VERSION%-branch}.0
          
          # Update gen-sdk.sh
          sed -i "s/VERSION=.*/VERSION=$VERSION/" hack/python-sdk/gen-sdk.sh
          
          # Update swagger_config.json
          sed -i "s/\"packageVersion\": \"[^\"]*\"/\"packageVersion\": \"$VERSION\"/" hack/python-sdk/swagger_config.json
          
          # Update setup.py
          sed -i "s/version=\"[^\"]*\"/version=\"$VERSION\"/" sdk/python/setup.py
      
      - name: Generate Training SDK
        run: make generate
      
      - name: Package SDK
        working-directory: sdk/python
        run: python3 setup.py sdist bdist_wheel
      
      - name: Upload SDK to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        working-directory: sdk/python
        run: twine upload dist/*