name: Release Training SDK

on:
  workflow_run:
    workflows:
      - Create Release Branch
    types:
      - completed

jobs:
  release-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install PyGithub==1.55 twine==3.4.1

      - name: Extract version from branch name
        id: extract_version
        run: |
          # Extract version from branch name
          BRANCH_NAME=${GITHUB_REF_NAME}
          if [[ "$BRANCH_NAME" =~ ^v([0-9]+\.[0-9]+)-branch$ ]]; then
            VERSION="${BASH_REMATCH[1]}.0"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "Invalid branch name format. Expected 'vX.Y-branch'."
            exit 1
          fi

      - name: Update version in SDK files
        run: |
          sed -i "s/VERSION=.*/VERSION=${VERSION}/" hack/python-sdk/gen-sdk.sh
          sed -i "s/packageVersion:.*/packageVersion: ${VERSION}/" hack/python-sdk/swagger_config.json
          sed -i "s/version=.*/version='${VERSION}'/" sdk/python/setup.py

      - name: Generate Training SDK
        run: make generate

      - name: Package SDK
        working-directory: sdk/python
        run: python3 setup.py sdist bdist_wheel

      - name: Upload SDK to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        working-directory: sdk/python
        run: twine upload dist/*
